In [1]:
import torch

#### Создайте случайный FloatTensor размера 3x4x5

In [2]:
a = torch.FloatTensor(3, 4, 5)
a

tensor([[[3.9651e-20, 8.6180e-43, 3.9651e-20, 8.6180e-43, 3.9667e-20],
         [8.6180e-43, 3.9667e-20, 8.6180e-43, 1.4107e-21, 8.6180e-43],
         [1.4107e-21, 8.6180e-43, 3.9659e-20, 8.6180e-43, 3.9659e-20],
         [8.6180e-43, 1.4107e-21, 8.6180e-43, 1.4107e-21, 8.6180e-43]],

        [[3.9639e-20, 8.6180e-43, 5.4273e-21, 8.6180e-43, 1.4107e-21],
         [8.6180e-43, 1.4107e-21, 8.6180e-43, 3.9610e-20, 8.6180e-43],
         [3.9610e-20, 8.6180e-43, 3.9597e-20, 8.6180e-43, 5.4266e-21],
         [8.6180e-43, 3.9708e-20, 8.6180e-43, 3.9708e-20, 8.6180e-43]],

        [[5.4301e-21, 8.6180e-43, 5.4301e-21, 8.6180e-43, 5.4185e-21],
         [8.6180e-43, 5.4185e-21, 8.6180e-43, 3.9697e-20, 8.6180e-43],
         [3.9697e-20, 8.6180e-43, 5.4285e-21, 8.6180e-43, 5.4285e-21],
         [8.6180e-43, 5.4276e-21, 8.6180e-43, 5.4276e-21, 8.6180e-43]]])

#### Выведите его форму (shape)

In [3]:
a.shape

torch.Size([3, 4, 5])

#### Приведите его к форме 6 X 10

In [4]:
a.view(6, 10)

tensor([[3.9651e-20, 8.6180e-43, 3.9651e-20, 8.6180e-43, 3.9667e-20, 8.6180e-43,
         3.9667e-20, 8.6180e-43, 1.4107e-21, 8.6180e-43],
        [1.4107e-21, 8.6180e-43, 3.9659e-20, 8.6180e-43, 3.9659e-20, 8.6180e-43,
         1.4107e-21, 8.6180e-43, 1.4107e-21, 8.6180e-43],
        [3.9639e-20, 8.6180e-43, 5.4273e-21, 8.6180e-43, 1.4107e-21, 8.6180e-43,
         1.4107e-21, 8.6180e-43, 3.9610e-20, 8.6180e-43],
        [3.9610e-20, 8.6180e-43, 3.9597e-20, 8.6180e-43, 5.4266e-21, 8.6180e-43,
         3.9708e-20, 8.6180e-43, 3.9708e-20, 8.6180e-43],
        [5.4301e-21, 8.6180e-43, 5.4301e-21, 8.6180e-43, 5.4185e-21, 8.6180e-43,
         5.4185e-21, 8.6180e-43, 3.9697e-20, 8.6180e-43],
        [3.9697e-20, 8.6180e-43, 5.4285e-21, 8.6180e-43, 5.4285e-21, 8.6180e-43,
         5.4276e-21, 8.6180e-43, 5.4276e-21, 8.6180e-43]])

#### Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно

In [5]:
b = torch.FloatTensor([1, 4, 2, 2, 1])

In [6]:
a * b

tensor([[[3.9651e-20, 3.4472e-42, 7.9301e-20, 1.7236e-42, 3.9667e-20],
         [8.6180e-43, 1.5867e-19, 1.7236e-42, 2.8215e-21, 8.6180e-43],
         [1.4107e-21, 3.4472e-42, 7.9317e-20, 1.7236e-42, 3.9659e-20],
         [8.6180e-43, 5.6429e-21, 1.7236e-42, 2.8215e-21, 8.6180e-43]],

        [[3.9639e-20, 3.4472e-42, 1.0855e-20, 1.7236e-42, 1.4107e-21],
         [8.6180e-43, 5.6429e-21, 1.7236e-42, 7.9220e-20, 8.6180e-43],
         [3.9610e-20, 3.4472e-42, 7.9194e-20, 1.7236e-42, 5.4266e-21],
         [8.6180e-43, 1.5883e-19, 1.7236e-42, 7.9417e-20, 8.6180e-43]],

        [[5.4301e-21, 3.4472e-42, 1.0860e-20, 1.7236e-42, 5.4185e-21],
         [8.6180e-43, 2.1674e-20, 1.7236e-42, 7.9393e-20, 8.6180e-43],
         [3.9697e-20, 3.4472e-42, 1.0857e-20, 1.7236e-42, 5.4285e-21],
         [8.6180e-43, 2.1710e-20, 1.7236e-42, 1.0855e-20, 8.6180e-43]]])

In [7]:
a.mul(b)

tensor([[[3.9651e-20, 3.4472e-42, 7.9301e-20, 1.7236e-42, 3.9667e-20],
         [8.6180e-43, 1.5867e-19, 1.7236e-42, 2.8215e-21, 8.6180e-43],
         [1.4107e-21, 3.4472e-42, 7.9317e-20, 1.7236e-42, 3.9659e-20],
         [8.6180e-43, 5.6429e-21, 1.7236e-42, 2.8215e-21, 8.6180e-43]],

        [[3.9639e-20, 3.4472e-42, 1.0855e-20, 1.7236e-42, 1.4107e-21],
         [8.6180e-43, 5.6429e-21, 1.7236e-42, 7.9220e-20, 8.6180e-43],
         [3.9610e-20, 3.4472e-42, 7.9194e-20, 1.7236e-42, 5.4266e-21],
         [8.6180e-43, 1.5883e-19, 1.7236e-42, 7.9417e-20, 8.6180e-43]],

        [[5.4301e-21, 3.4472e-42, 1.0860e-20, 1.7236e-42, 5.4185e-21],
         [8.6180e-43, 2.1674e-20, 1.7236e-42, 7.9393e-20, 8.6180e-43],
         [3.9697e-20, 3.4472e-42, 1.0857e-20, 1.7236e-42, 5.4285e-21],
         [8.6180e-43, 2.1710e-20, 1.7236e-42, 1.0855e-20, 8.6180e-43]]])

#### Умножьте тензор матрично на себя, чтобы результат был размерности 6x6

In [8]:
a.view(6, 10).mm(a.view(6, 10).T)

tensor([[6.2933e-39, 3.2595e-39, 1.9547e-39, 4.9870e-39, 9.1649e-40, 2.2275e-39],
        [3.2595e-39, 3.1516e-39, 3.8498e-40, 1.9535e-39, 5.0155e-40, 5.0189e-40],
        [1.9547e-39, 3.8498e-40, 3.1736e-39, 3.4215e-39, 1.8324e-39, 1.8333e-39],
        [4.9870e-39, 1.9535e-39, 3.4215e-39, 6.3199e-39, 2.2510e-39, 2.2478e-39],
        [9.1649e-40, 5.0155e-40, 1.8324e-39, 2.2510e-39, 1.6935e-39, 5.1932e-40],
        [2.2275e-39, 5.0189e-40, 1.8333e-39, 2.2478e-39, 5.1932e-40, 1.6937e-39]])

In [9]:
a.view(6, 10) @ a.view(6, 10).T

tensor([[6.2933e-39, 3.2595e-39, 1.9547e-39, 4.9870e-39, 9.1649e-40, 2.2275e-39],
        [3.2595e-39, 3.1516e-39, 3.8498e-40, 1.9535e-39, 5.0155e-40, 5.0189e-40],
        [1.9547e-39, 3.8498e-40, 3.1736e-39, 3.4215e-39, 1.8324e-39, 1.8333e-39],
        [4.9870e-39, 1.9535e-39, 3.4215e-39, 6.3199e-39, 2.2510e-39, 2.2478e-39],
        [9.1649e-40, 5.0155e-40, 1.8324e-39, 2.2510e-39, 1.6935e-39, 5.1932e-40],
        [2.2275e-39, 5.0189e-40, 1.8333e-39, 2.2478e-39, 5.1932e-40, 1.6937e-39]])

#### Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [10]:
from torch.autograd import Variable
x = Variable(torch.FloatTensor([1]), requires_grad = True)
z = Variable(torch.FloatTensor([0.5]), requires_grad = True)
t = Variable(torch.FloatTensor([2]), requires_grad = True)

In [11]:
y = x**3 + z - 75*t

In [12]:
y.backward()

In [13]:
print(x.grad)
print(z.grad)
print(t.grad)

tensor([3.])
tensor([1.])
tensor([-75.])


#### Создайте единичный тензор размера 5x6

In [14]:
c = torch.ones(5, 6)
c

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

#### Переведите его в формат numpy

In [15]:
c = c.numpy()
type(c)

numpy.ndarray